### ISSUE TITLE
Re-enable export_mv_grid for visualization purposes

### ISSUE THREAD

**Issue by gplssm** [openego/dingo#73]
Due to an error not understood, I commented out "export for visualization" purposes. See the error

```
Traceback (most recent call last):
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
psycopg2.DataError: Geometry type (GeometryCollection) does not match column type (MultiPoint)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/guido/rli_local/dingo/test_dingo2.py", line 47, in <module>
    nd.export_mv_grid(conn, mv_grid_districts)
  File "/home/guido/rli_local/dingo/dingo/core/__init__.py", line 762, in export_mv_grid
    session.commit()
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 874, in commit
    self.transaction.commit()
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2137, in flush
    self._flush(objects)
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2257, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2221, in _flush
    flush_context.execute()
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 176, in save_obj
    mapper, table, insert)
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 827, in _emit_insert_statements
    params)
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/guido/virtualenvs/dingo/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.DataError) Geometry type (GeometryCollection) does not match column type (MultiPoint)
 [SQL: 'INSERT INTO calc_ego_grid.ego_deu_mv_grids_vis (grid_id, geom_mv_station, geom_mv_cable_dists, geom_mv_circuit_breakers, geom_lv_load_area_centres, geom_lv_stations, geom_mv_generators, geom_mv_lines) VALUES (%(grid_id)s, ST_GeomFromWKB(%(ST_GeomFromWKB_1)s, %(ST_GeomFromWKB_2)s), ST_GeomFromWKB(%(ST_GeomFromWKB_3)s, %(ST_GeomFromWKB_4)s), ST_GeomFromWKB(%(ST_GeomFromWKB_5)s, %(ST_GeomFromWKB_6)s), ST_GeomFromWKB(%(ST_GeomFromWKB_7)s, %(ST_GeomFromWKB_8)s), ST_GeomFromWKB(%(ST_GeomFromWKB_9)s, %(ST_GeomFromWKB_10)s), ST_GeomFromWKB(%(ST_GeomFromWKB_11)s, %(ST_GeomFromWKB_12)s), ST_GeomFromWKB(%(ST_GeomFromWKB_13)s, %(ST_GeomFromWKB_14)s))'] [parameters: {'ST_GeomFromWKB_8': '4326', 'ST_GeomFromWKB_1': <memory at 0x7fbdfd0fb9a8>, 'ST_GeomFromWKB_10': '4326', 'ST_GeomFromWKB_12': '4326', 'grid_id': 360, 'ST_GeomFromWKB_2': '4326', 'ST_GeomFromWKB_13': <memory at 0x7fbdfe870f20>, 'ST_GeomFromWKB_3': <memory at 0x7fbdfd0fbcc8>, 'ST_GeomFromWKB_9': <memory at 0x7fbdfd0fbe58>, 'ST_GeomFromWKB_7': <memory at 0x7fbdfd0fbd90>, 'ST_GeomFromWKB_14': '4326', 'ST_GeomFromWKB_5': <memory at 0x7fbdfd0fbc00>, 'ST_GeomFromWKB_4': '4326', 'ST_GeomFromWKB_6': '4326', 'ST_GeomFromWKB_11': <memory at 0x7fbdfd0fb8e0>}]

```

Once, we have a clou why one of the variables has now type `GeometryCollection`, we may solve it and revert 448407a3ef4cfcacb60c5818b611a48d6b08972f

**Comment by gplssm** [comment]
Fix some issues related to "new" data structure which this as well.
